/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admindashboard;

import Config.DBConnector;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author scc-college
 */
public class Payment extends javax.swing.JInternalFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        viewdetails();
    }
    DefaultTableModel model;
       private Connection connect;
   public void viewdetails(){
        try {
             connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/renatal", "root", "");
             Statement st = connect.createStatement();
             ResultSet rs = st.executeQuery("select * from issue");
             
             while(rs.next()){
               String is_id = rs.getString("is_id");
             String houseID = rs.getString("h_id");
             String rentID = rs.getString("o_id");
             String started = rs.getString("started_date");
             String duedate = rs.getString("end_date");
             String status = rs.getString("is_status");
             
             Object [] obj = {is_id,houseID,rentID,started,duedate,status};
             model = (DefaultTableModel) h_table.getModel();
             model.addRow(obj);
             
             }
             
             
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    
    }
    public void cleartable(){
    DefaultTableModel model =(DefaultTableModel)h_table.getModel();
    model.setRowCount(0);
     
  
  
      try {
           connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/renatal", "root", "");
           String sql = "select * from issue where started_date BETWEEN ? and ?";
           PreparedStatement pst = connect.prepareStatement(sql);
          ResultSet rs = pst.executeQuery();
          if(rs.next() == false){
          JOptionPane.showMessageDialog(this, "NO RECORDS FOUND");
          
          }else{
          
          
             while(rs.next()){
               String is_id = rs.getString("is_id");
             String houseID = rs.getString("h_id");
             String rentID = rs.getString("o_id");
             String started = rs.getString("started_date");
             String duedate = rs.getString("end_date");
             String status = rs.getString("is_status");
             
             Object [] obj = {is_id,houseID,rentID,started,duedate,status};
             model = (DefaultTableModel) h_table.getModel();
             model.addRow(obj);
             
          }
          }  
      } catch (Exception e) {
      e.printStackTrace();
      
      }
  }
  
   public void filter(String qry ){
             model = (DefaultTableModel) h_table.getModel();
         TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
         h_table.setRowSorter(trs);
       
         if(qry =="ALL"){
        h_table.setRowSorter(trs);
         }else{
         trs.setRowFilter(RowFilter.regexFilter(qry));
         }
       
       }

    Color navcolor = new Color(255, 204, 255);
    Color hovercolor = new Color(0,0,51);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        h_table = new javax.swing.JTable();
        p_add2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        p_add3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        p_add4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TENANTS RECORD");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 370, 50));

        h_table.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        h_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        h_table.setGridColor(new java.awt.Color(204, 0, 102));
        h_table.setRowHeight(25);
        h_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                h_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(h_table);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 840, 280));

        p_add2.setBackground(new java.awt.Color(255, 204, 255));
        p_add2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add2MouseExited(evt);
            }
        });
        p_add2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PRINT");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        p_add2.add(jLabel8);
        jLabel8.setBounds(20, 20, 100, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-print-20.png"))); // NOI18N
        p_add2.add(jLabel2);
        jLabel2.setBounds(50, 0, 30, 30);

        jPanel2.add(p_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 140, 50));

        search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        search.setText("SEARCH");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchMouseReleased(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel2.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 610, 30));

        p_add3.setBackground(new java.awt.Color(255, 204, 255));
        p_add3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add3MouseExited(evt);
            }
        });
        p_add3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("VIEW ALL ");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        p_add3.add(jLabel9);
        jLabel9.setBounds(10, 0, 130, 50);

        jPanel2.add(p_add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 150, 50));

        p_add4.setBackground(new java.awt.Color(255, 204, 255));
        p_add4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_add4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_add4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_add4MouseExited(evt);
            }
        });
        p_add4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BACK ");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        p_add4.add(jLabel10);
        jLabel10.setBounds(30, 0, 110, 50);

        jPanel2.add(p_add4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void h_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_h_tableMouseClicked

    }//GEN-LAST:event_h_tableMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        MessageFormat head = new MessageFormat("RECORDS");
        MessageFormat FOOT = new MessageFormat("Page{0, number , integer}");

        try {
            h_table.print(JTable.PrintMode.NORMAL, head, FOOT);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "cannot print");
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void p_add2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseClicked

    }//GEN-LAST:event_p_add2MouseClicked

    private void p_add2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseEntered
          p_add2.setBackground(hovercolor);
    }//GEN-LAST:event_p_add2MouseEntered

    private void p_add2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add2MouseExited
          p_add2.setBackground(navcolor);
    }//GEN-LAST:event_p_add2MouseExited

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        search.setText("");
    }//GEN-LAST:event_searchMouseClicked

    private void searchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseReleased

    }//GEN-LAST:event_searchMouseReleased

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        DefaultTableModel tbl = (DefaultTableModel) h_table.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(tbl);
        h_table.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(search.getText()));
    }//GEN-LAST:event_searchKeyReleased

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
         cleartable();
         viewdetails();
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void p_add3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add3MouseClicked

    }//GEN-LAST:event_p_add3MouseClicked

    private void p_add3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add3MouseEntered
        p_add3.setBackground(hovercolor);

    }//GEN-LAST:event_p_add3MouseEntered

    private void p_add3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add3MouseExited
        p_add3.setBackground(navcolor);

    }//GEN-LAST:event_p_add3MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void p_add4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add4MouseClicked
       Admin ad = new Admin();
       ad.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_p_add4MouseClicked

    private void p_add4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add4MouseEntered

    private void p_add4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_add4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_p_add4MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable h_table;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel p_add2;
    private javax.swing.JPanel p_add3;
    private javax.swing.JPanel p_add4;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
